workflows:
    b2b_flow_checkout_with_consents:
        transitions:
            __start__:
                is_start: true
                is_hidden: true
                transition_definition: __start___definition

            finish_checkout:
                transition_definition: finish_checkout_definition
                is_hidden: true

            payment_error:
                transition_definition: unblock_and_recalculate_definition
                is_hidden: true
