workflows:
    b2b_flow_checkout_with_consents:
        steps:
            customer_consents:
                order: 5
                allowed_transitions:
                    - start_from_quickorderform
                    - continue_to_billing_address
            enter_billing_address:
                order: 10
                allowed_transitions:
                    - back_to_customer_consents
                    - continue_to_shipping_address
            enter_shipping_address:
                order: 20
                allowed_transitions:
                    - continue_to_shipping_method
                    - back_to_billing_address
                    - back_to_customer_consents
            enter_shipping_method:
                order: 30
                allowed_transitions:
                    - continue_to_payment
                    - back_to_billing_address
                    - back_to_shipping_address
                    - back_to_customer_consents
            enter_payment:
                order: 40
                allowed_transitions:
                    - payment_error
                    - continue_to_order_review
                    - back_to_billing_address
                    - back_to_shipping_address
                    - back_to_shipping_method
                    - back_to_customer_consents
            order_review:
                order: 50
                allowed_transitions:
                    - place_order
                    - verify_payment
                    - finish_checkout
                    - payment_error
                    - back_to_billing_address
                    - back_to_shipping_address
                    - back_to_shipping_method
                    - back_to_payment
                    - back_to_shipping_address_on_fail_address
                    - back_to_customer_consents
            order_created:
                order: 60
                is_final: true
