features:
    consents:
        label: oro.consent.feature.label
        description: oro.consent.feature.description
        toggle: oro_consent.consent_feature_enabled
        routes:
            - 'oro_consent_index'
            - 'oro_consent_create'
            - 'oro_consent_update'
            - 'oro_consent_view'
            - 'oro_consent_info'
            - 'oro_api_consent_webcatalog_tree_get'
        configuration:
            - 'enabled_consents'
