query_designer:
    filters:
        consents:
             applicable: [{entity: OroCustomerBundle:CustomerUser, field: acceptedConsents}]
             type:       accepted_consents
             query_type: [all]
