oro_consent:
    resource:     "@OroConsentBundle/Controller/ConsentController.php"
    type:         annotation
    prefix:       /consent

oro_web_catalog_bundle_api:
    resource:     "@OroConsentBundle/Resources/config/oro/routing_api.yml"
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest
