imports:
    - { resource: 'b2b_flow_checkout_with_consents/transitions.yml' }
    - { resource: 'b2b_flow_checkout_with_consents/transition_definitions.yml' }
    - { resource: 'b2b_flow_checkout_with_consents/steps.yml' }
    - { resource: 'b2b_flow_checkout_with_consents/attributes.yml' }
    - { resource: 'b2b_flow_checkout_with_consents/base_transition_definitions.yml' }
    - { resource: 'b2b_flow_checkout_with_consents/base_transitions.yml' }

workflows:
    b2b_flow_checkout_with_consents:
        entity: Oro\Bundle\CheckoutBundle\Entity\Checkout
        entity_attribute: checkout
        steps_display_ordered: true

        defaults:
            active: false

        applications: ['commerce']

        exclusive_active_groups:
            - b2b_checkout_flow
        exclusive_record_groups:
            - b2b_checkout_flow

        priority: 200
