styles:
    inputs:
        - 'bundles/oroconsent/blank/scss/variables/consent-customer-profile-config.scss'
        - 'bundles/oroconsent/blank/scss/variables/consent-dialog-widget-config.scss'
        - 'bundles/oroconsent/blank/scss/variables/consent-item-config.scss'
        - 'bundles/oroconsent/blank/scss/variables/consent-list-config.scss'

        - 'bundles/oroconsent/blank/scss/styles.scss'
