action_groups:
    b2b_flow_checkout_create_guest_customer_user_with_consents:
        parameters:
            checkout:
                type: Oro\Bundle\CheckoutBundle\Entity\Checkout
            visitor_email:
                default: null
            billing_address:
                default: null
        actions:
            - '@tree':
                conditions:
                    '@empty': $.checkout.customerUser
                actions:
                    - '@get_active_visitor': $visitor
                    - '@call_service_method':
                        attribute: $.checkout.customerUser
                        service: 'oro_customer.manager.guest_customer_user'
                        method: createFromAddress
                        method_parameters:
                            - $.visitor_email
                            - $.billing_address
                    - '@flush_entity': $.checkout.customerUser
                    - '@call_service_method':
                        service: 'oro_consent.manager.guest_customer_consent_acceptances_manager'
                        method: flushCustomerConsentAcceptancesFromStorage
                        method_parameters:
                            - $.checkout.customerUser
                    - '@assign_value': [$visitor.customerUser, $.checkout.customerUser]
                    - '@flush_entity': $visitor
